{
    "data":{
    "id":"10.20408/7v8w-ky38",
        "type":"dois",
        "attributes":{
        "doi":"10.20408/7v8w-ky38",
            "prefix":"10.20408",
            "suffix":"7v8w-ky38",
            "identifiers":null,
            "creators":[

        ],
            "titles":null,
            "publisher":null,
            "container":{

        },
        "publicationYear":null,
            "subjects":null,
            "contributors":[

        ],
            "dates":null,
            "language":null,
            "types":{

        },
        "relatedIdentifiers":null,
            "sizes":null,
            "formats":null,
            "version":null,
            "rightsList":[

        ],
            "descriptions":null,
            "geoLocations":null,
            "fundingReferences":null,
            "xml":null,
            "url":null,
            "contentUrl":null,
            "metadataVersion":0,
            "schemaVersion":null,
            "source":null,
            "isActive":false,
            "state":"draft",
            "reason":null,
            "landingPage":null,
            "created":"2019-09-26T10:52:35.000Z",
            "registered":null,
            "published":"",
            "updated":"2019-09-26T10:52:35.000Z"
    },
    "relationships":{
        "client":{
            "data":{
                "id":"dev.fit",
                    "type":"clients"
            }
        },
        "media":{
            "data":{
                "id":"10.20408/7v8w-ky38",
                    "type":"media"
            }
        }
    }
},
    "included":[
    {
        "id":"dev.fit",
        "type":"clients",
        "attributes":{
            "name":"Fraunhofer FIT",
            "symbol":"DEV.FIT",
            "year":2019,
            "contactEmail":"joao.bosco.jares.alves.chaves@fit.fraunhofer.de",
            "alternateName":null,
            "description":null,
            "language":null,
            "clientType":"repository",
            "domains":"*",
            "issn":null,
            "url":"https://www.fit.fraunhofer.de/",
            "created":"2019-06-17T14:28:30.000Z",
            "updated":"2019-06-20T12:08:39.000Z",
            "isActive":true,
            "hasPassword":true
        },
        "relationships":{
            "provider":{
                "data":{
                    "id":"dev",
                    "type":"providers"
                }
            },
            "prefixes":{
                "data":[
                    {
                        "id":"10.20408",
                        "type":"prefixes"
                    }
                ]
            }
        }
    }
]
}